import type {
  WorkflowSummary, WorkflowTemplate,
} from './workflow-home-types';

const NOW = Date.now();
const ago = (h: number) => NOW - h * 3600_000;

// ── Mock workflow summaries ────────────────────────────────────────────────────

export const MOCK_WORKFLOW_SUMMARIES: WorkflowSummary[] = [
  {
    id: 'wf-001',
    name: 'Jira Comment RCA',
    description: 'When a Jira ticket exceeds 20 comments, run root cause analysis and notify the PM via Slack.',
    status: 'active',
    trigger: { type: 'event', connector: 'jira', event: 'jira:comment_added', label: 'Jira Comment Added' },
    agents: [{ agentId: 'engineering', agentName: 'Engineering Agent' }],
    connectors: [
      { connectorId: 'jira',   label: 'Jira'   },
      { connectorId: 'notion', label: 'Notion'  },
      { connectorId: 'slack',  label: 'Slack'   },
    ],
    lastRun: { runId: 'run-101', startedAt: ago(2), completedAt: ago(2) + 14000, status: 'completed', triggeredBy: 'event', stepsCompleted: 7, stepsTotal: 7 },
    successRate: 0.94,
    totalRuns: 47,
    owner: 'Aashish Gupta',
    createdAt: ago(720),
    updatedAt: ago(48),
    tags: ['incident', 'rca', 'jira'],
  },
  {
    id: 'wf-002',
    name: 'Weekly Sprint Summary',
    description: 'Every Monday at 9am, summarise sprint progress and post to Confluence and Slack.',
    status: 'active',
    trigger: { type: 'schedule', schedule: '0 9 * * 1', label: 'Every Monday 9am' },
    agents: [{ agentId: 'ops', agentName: 'Sprint Planner' }],
    connectors: [
      { connectorId: 'jira',        label: 'Jira'        },
      { connectorId: 'confluence',  label: 'Confluence'  },
      { connectorId: 'slack',       label: 'Slack'       },
    ],
    lastRun: { runId: 'run-102', startedAt: ago(72), completedAt: ago(72) + 9000, status: 'completed', triggeredBy: 'schedule', stepsCompleted: 5, stepsTotal: 5 },
    successRate: 1.0,
    totalRuns: 24,
    owner: 'Priya K.',
    createdAt: ago(1440),
    updatedAt: ago(72),
    tags: ['sprint', 'reporting'],
  },
  {
    id: 'wf-003',
    name: 'Metric Drop Alert',
    description: 'When activation rate drops more than 10%, trigger an analytics investigation and alert the team.',
    status: 'active',
    trigger: { type: 'event', connector: 'amplitude', event: 'amplitude:metric_threshold', label: 'Metric Threshold Breached' },
    agents: [{ agentId: 'analytics', agentName: 'Analytics Agent' }],
    connectors: [
      { connectorId: 'amplitude', label: 'Amplitude' },
      { connectorId: 'slack',     label: 'Slack'     },
    ],
    lastRun: { runId: 'run-103', startedAt: ago(1), completedAt: ago(1) + 8000, status: 'completed', triggeredBy: 'event', stepsCompleted: 4, stepsTotal: 4 },
    successRate: 0.88,
    totalRuns: 31,
    owner: 'Aashish Gupta',
    createdAt: ago(500),
    updatedAt: ago(24),
    tags: ['metrics', 'analytics', 'alert'],
  },
  {
    id: 'wf-004',
    name: 'PRD Creation Pipeline',
    description: 'When an epic is created in Jira, draft a PRD using the Docs Writer agent and send for PM review.',
    status: 'draft',
    trigger: { type: 'event', connector: 'jira', event: 'jira:epic_created', label: 'Epic Created' },
    agents: [{ agentId: 'docs', agentName: 'Docs Writer' }],
    connectors: [
      { connectorId: 'jira',   label: 'Jira'   },
      { connectorId: 'notion', label: 'Notion'  },
    ],
    lastRun: undefined,
    successRate: 0,
    totalRuns: 0,
    owner: 'Aashish Gupta',
    createdAt: ago(48),
    updatedAt: ago(12),
    tags: ['prd', 'docs', 'epic'],
  },
  {
    id: 'wf-005',
    name: 'Competitor Monitoring',
    description: 'Every Monday, scan competitor updates and generate a battlecard diff for the product team.',
    status: 'paused',
    trigger: { type: 'schedule', schedule: '0 8 * * 1', label: 'Every Monday 8am' },
    agents: [{ agentId: 'competitive', agentName: 'Competitive Intel' }],
    connectors: [
      { connectorId: 'notion', label: 'Notion' },
      { connectorId: 'slack',  label: 'Slack'  },
    ],
    lastRun: { runId: 'run-105', startedAt: ago(168), completedAt: ago(168) + 22000, status: 'completed', triggeredBy: 'schedule', stepsCompleted: 4, stepsTotal: 4 },
    successRate: 0.79,
    totalRuns: 14,
    owner: 'Sarah Chen',
    createdAt: ago(900),
    updatedAt: ago(168),
    tags: ['competitive', 'battlecard'],
  },
  {
    id: 'wf-006',
    name: 'Churn Risk Detection',
    description: 'When a key account shows declining engagement in Amplitude, alert the CS team and create a Jira task.',
    status: 'error',
    trigger: { type: 'event', connector: 'amplitude', event: 'amplitude:metric_threshold', label: 'Engagement Drop' },
    agents: [{ agentId: 'analytics', agentName: 'Analytics Agent' }],
    connectors: [
      { connectorId: 'amplitude', label: 'Amplitude' },
      { connectorId: 'jira',      label: 'Jira'      },
      { connectorId: 'slack',     label: 'Slack'     },
    ],
    lastRun: { runId: 'run-106', startedAt: ago(5), completedAt: ago(5) + 3000, status: 'failed', triggeredBy: 'event', stepsCompleted: 2, stepsTotal: 5 },
    successRate: 0.61,
    totalRuns: 18,
    owner: 'Tom B.',
    createdAt: ago(600),
    updatedAt: ago(5),
    tags: ['churn', 'cs', 'amplitude'],
  },
  {
    id: 'wf-007',
    name: 'Release Readiness Check',
    description: 'Before each deployment, run a go/no-go assessment and notify stakeholders of the decision.',
    status: 'active',
    trigger: { type: 'event', connector: 'github', event: 'github:deployment_completed', label: 'Deployment Event' },
    agents: [{ agentId: 'release', agentName: 'Release Manager' }],
    connectors: [
      { connectorId: 'github', label: 'GitHub' },
      { connectorId: 'jira',   label: 'Jira'   },
      { connectorId: 'slack',  label: 'Slack'  },
    ],
    lastRun: { runId: 'run-107', startedAt: ago(8), completedAt: ago(8) + 11000, status: 'completed', triggeredBy: 'event', stepsCompleted: 6, stepsTotal: 6 },
    successRate: 0.97,
    totalRuns: 63,
    owner: 'Alex M.',
    createdAt: ago(800),
    updatedAt: ago(8),
    tags: ['release', 'go-no-go', 'github'],
  },
  {
    id: 'wf-008',
    name: 'Backlog Prioritization',
    description: 'Every Friday, rank the top 20 backlog items by impact and effort and post the ranked list to Notion.',
    status: 'active',
    trigger: { type: 'schedule', schedule: '0 17 * * 5', label: 'Every Friday 5pm' },
    agents: [{ agentId: 'prioritization', agentName: 'Prioritization Agent' }],
    connectors: [
      { connectorId: 'jira',   label: 'Jira'   },
      { connectorId: 'notion', label: 'Notion'  },
    ],
    lastRun: { runId: 'run-108', startedAt: ago(48), completedAt: ago(48) + 7000, status: 'completed', triggeredBy: 'schedule', stepsCompleted: 3, stepsTotal: 3 },
    successRate: 0.92,
    totalRuns: 19,
    owner: 'Priya K.',
    createdAt: ago(400),
    updatedAt: ago(48),
    tags: ['prioritization', 'backlog'],
  },
];

// ── Workflow templates ─────────────────────────────────────────────────────────

export const WORKFLOW_TEMPLATES: WorkflowTemplate[] = [
  {
    id: 'tpl-jira-rca',
    name: 'Jira Comment RCA',
    description: 'Fires when comment count exceeds a threshold, runs root cause analysis, and notifies PM via Slack.',
    category: 'Incident Response',
    trigger: { type: 'event', connector: 'jira', event: 'jira:comment_added', label: 'Jira Comment Added' },
    estimatedNodes: 7,
    agents: [{ agentId: 'engineering', agentName: 'Engineering Agent' }],
    connectors: [
      { connectorId: 'jira',   label: 'Jira'   },
      { connectorId: 'notion', label: 'Notion'  },
      { connectorId: 'slack',  label: 'Slack'   },
    ],
    tags: ['incident', 'rca'],
    nlPrompt: 'When a Jira ticket has more than 20 comments, analyze it with the RCA agent, create a Notion page and notify the PM via Slack',
  },
  {
    id: 'tpl-sprint-summary',
    name: 'Weekly Sprint Summary',
    description: 'Every Monday, generates a sprint progress summary and posts it to Confluence and Slack.',
    category: 'Sprint & Planning',
    trigger: { type: 'schedule', schedule: '0 9 * * 1', label: 'Every Monday 9am' },
    estimatedNodes: 4,
    agents: [{ agentId: 'ops', agentName: 'Sprint Planner' }],
    connectors: [
      { connectorId: 'jira',       label: 'Jira'       },
      { connectorId: 'confluence', label: 'Confluence'  },
      { connectorId: 'slack',      label: 'Slack'       },
    ],
    tags: ['sprint', 'reporting'],
    nlPrompt: 'Every Monday morning, summarise sprint progress and post to Confluence and notify the team on Slack',
  },
  {
    id: 'tpl-metric-drop',
    name: 'Metric Drop Alert',
    description: 'Detects when a key metric drops below threshold, runs analysis, and alerts the product team.',
    category: 'Analytics',
    trigger: { type: 'event', connector: 'amplitude', event: 'amplitude:metric_threshold', label: 'Metric Threshold Breached' },
    estimatedNodes: 4,
    agents: [{ agentId: 'analytics', agentName: 'Analytics Agent' }],
    connectors: [
      { connectorId: 'amplitude', label: 'Amplitude' },
      { connectorId: 'slack',     label: 'Slack'     },
    ],
    tags: ['metrics', 'alert'],
    nlPrompt: 'When a metric drops by more than 10%, analyze the data and alert the product team on Slack',
  },
  {
    id: 'tpl-prd-pipeline',
    name: 'PRD Creation Pipeline',
    description: 'When a new epic is opened in Jira, drafts a PRD and routes it through PM approval before publishing.',
    category: 'Product',
    trigger: { type: 'event', connector: 'jira', event: 'jira:epic_created', label: 'Epic Created' },
    estimatedNodes: 5,
    agents: [{ agentId: 'docs', agentName: 'Docs Writer' }],
    connectors: [
      { connectorId: 'jira',   label: 'Jira'   },
      { connectorId: 'notion', label: 'Notion'  },
    ],
    tags: ['prd', 'docs'],
    nlPrompt: 'When an epic is created in Jira, draft a PRD using the docs agent, get PM approval, and publish to Notion',
  },
  {
    id: 'tpl-competitor',
    name: 'Competitor Monitoring',
    description: 'Weekly competitive intelligence sweep that generates a battlecard diff and posts to the product channel.',
    category: 'Competitive',
    trigger: { type: 'schedule', schedule: '0 8 * * 1', label: 'Every Monday 8am' },
    estimatedNodes: 3,
    agents: [{ agentId: 'competitive', agentName: 'Competitive Intel' }],
    connectors: [
      { connectorId: 'notion', label: 'Notion' },
      { connectorId: 'slack',  label: 'Slack'  },
    ],
    tags: ['competitive', 'battlecard'],
    nlPrompt: 'Every Monday, scan for competitor updates, generate a battlecard diff and notify the product team on Slack',
  },
  {
    id: 'tpl-churn-risk',
    name: 'Churn Risk Detection',
    description: 'When engagement drops for a key account, alerts CS team and creates a follow-up task in Jira.',
    category: 'Customer',
    trigger: { type: 'event', connector: 'amplitude', event: 'amplitude:metric_threshold', label: 'Engagement Drop' },
    estimatedNodes: 4,
    agents: [{ agentId: 'analytics', agentName: 'Analytics Agent' }],
    connectors: [
      { connectorId: 'amplitude', label: 'Amplitude' },
      { connectorId: 'jira',      label: 'Jira'      },
      { connectorId: 'slack',     label: 'Slack'     },
    ],
    tags: ['churn', 'cs'],
    nlPrompt: 'When a key account shows declining engagement in Amplitude, alert the CS team on Slack and create a Jira task',
  },
  {
    id: 'tpl-release-readiness',
    name: 'Release Readiness Check',
    description: 'Before each deployment, runs a go/no-go assessment and notifies all stakeholders with the decision.',
    category: 'Release',
    trigger: { type: 'event', connector: 'github', event: 'github:deployment_completed', label: 'Deployment Event' },
    estimatedNodes: 5,
    agents: [{ agentId: 'release', agentName: 'Release Manager' }],
    connectors: [
      { connectorId: 'github', label: 'GitHub' },
      { connectorId: 'jira',   label: 'Jira'   },
      { connectorId: 'slack',  label: 'Slack'  },
    ],
    tags: ['release', 'go-no-go'],
    nlPrompt: 'Before each deployment, run a go/no-go assessment and notify stakeholders on Slack with the decision',
  },
  {
    id: 'tpl-backlog-prioritization',
    name: 'Backlog Prioritization',
    description: 'Every Friday, ranks the top backlog items by impact and effort and publishes the list to Notion.',
    category: 'Sprint & Planning',
    trigger: { type: 'schedule', schedule: '0 17 * * 5', label: 'Every Friday 5pm' },
    estimatedNodes: 3,
    agents: [{ agentId: 'prioritization', agentName: 'Prioritization Agent' }],
    connectors: [
      { connectorId: 'jira',   label: 'Jira'   },
      { connectorId: 'notion', label: 'Notion'  },
    ],
    tags: ['prioritization', 'backlog'],
    nlPrompt: 'Every Friday, rank the top 20 backlog items by impact and effort and post the ranked list to Notion',
  },
];
